version: '3.3'

services:

 goods:
   build: ./goods
   command: bash -c "python ./goods/manage.py makemigrations goods && python ./goods/manage.py migrate && python ./goods/manage.py loaddata ./goods/goods/fixtures/mydata.json && python ./goods/manage.py runserver 0.0.0.0:8000"
   volumes:
     - .:/code
   ports:
     - "8000:8000"
   depends_on:
     - db

 notification_service:
    build: ./notification-service
    volumes:
      - ./notification-service:/src
    ports:
      - "8005:8005"
    depends_on:
      - db
      - rabbit
    environment:
      WAIT_HOSTS: db:5432, rabbit:5672

 db:
   image: postgres
   restart: always
   environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
 redis:
   image:  redis
   ports:
     - "6379:6379"
   command: redis-server --appendonly yes

 mail:
    image: bytemark/smtp
    restart: always
    environment:
      RELAY_HOST: smtp.yandex.ru
      RELAY_PORT: 587
      RELAY_USERNAME: username
      RELAY_PASSWORD: password

 rabbit:
   image: rabbitmq:3.6.6-management
   hostname: rabbit
   environment:
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
   ports:
     - "5672:5672"