version: '3.3'

services:

 goods:
   build: ./goods
   command: bash -c "python ./goods/manage.py makemigrations goods && python ./goods/manage.py migrate && python ./goods/manage.py loaddata ./goods/goods/fixtures/mydata.json && python ./goods/manage.py runserver 0.0.0.0:8000"
   volumes:
     - .:/code
   ports:
     - "8000:8000"
   depends_on:
     - db

 notification_service:
    build: ./notification-service
    command: /env/bin/uvicorn src.notification_service.asgi:app --reload --host 0.0.0.0 --port 8005
    volumes:
      - ./notification-service:/src
    ports:
      - "8005:8005"
    depends_on:
      - db
      - rabbit

 db:
   image: postgres
   restart: always
   environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
 redis:
   image:  redis
   ports:
     - "6379:6379"
   command: redis-server --appendonly yes

 rabbit:
   image: "rabbitmq:3-management"
   hostname: rabbit
   environment:
     RABBITMQ_ERLANG_COOKIE: "TESTVOLUME"
     RABBITMQ_DEFAULT_USER: "guest"
     RABBITMQ_DEFAULT_PASS: "guest"
   ports:
     - "15672:15672"
     - "5672:5672"
   volumes:
     - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
     - ./rabbitmq/logs:/var/log/rabbitmq/log