# Generated by Django 3.0.8 on 2020-07-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата размещения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.FileField(blank=True, null=True, upload_to='static/', verbose_name='Изображение')),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('tags', models.ManyToManyField(blank=True, to='goods.Tag')),
            ],
        ),
    ]
