"""add templates tables

Revision ID: 05827a483b0f
Revises: 
Create Date: 2020-08-13 14:26:40.793603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05827a483b0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    # ### end Alembic commands ###
